config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index"
  root to: "home#index"
  resources :recipes, only: [:index, :show]
  resources :categories, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
  validates :name, presence: true, uniqueness: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  # validates :name, presence:true
  validates :name, uniqueness:true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients


  validates :title, :directions, presence: true
  validates :title, uniqueness:true


  def recipe_params
    params.require(:recipe).permit(:title, :directions, :category_id, :search)
  end

  def self.search(search)
    if search
      recipe = Recipe.find_by(title: search)
      if recipe
        self.where(title: recipe)
      else
        Recipe.all
      end
    else
      Recipe.all
    end
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.includes(:recipes)
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    # @recipes = Recipe.includes(:category).paginate(:page => params[:page], :per_page => 30)
    if params[:search]
      @recipes = Recipe.where('title LIKE ?', "%#{params[:search]}%").paginate(:page => params[:page], :per_page => 30)
    else
      @recipes = Recipe.includes(:category).paginate(:page => params[:page], :per_page => 30)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/about/index.html.erb
<div class="tile is-ancestor">
  <div class="tile is-4 is-vertical is-parent">
    <div class="tile is-child box">
      <p class="title">ERD</p>
      <p><%= image_tag "RecipeERD.drawio.png", alt: "img"  %></p>
    </div>
  </div>
  <div class="tile is-parent">
    <div class="tile is-child box">
      <p class="title">Description</p>
        <p>The data presented here includes variety of culinary recipes. Dataset was loaded from CSV file source. The dataset used for this project includes the title of the recipe, directions, different ingredients needed to prepare the recipe and the category of the recipe.
        <br>
        <br>
          <p>There are 4 tables in total as following:</p>
        <br>
        <p><strong>Recipe:</strong> id, title, directions, category_id</p>
        <p><strong>Category:</strong> id, name</p>
        <p><strong>Recipe Ingredients:</strong> recipe_id, ingredient_id</p>
        <p><strong>Ingredient:</strong> id, name</p>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="title is-1">Choose your Category:</h1>

<div class="columns">
  <div class="column">
  <figure class="image is-16by9">
      <iframe class="has-ratio" width="640" height="360" src="https://images.unsplash.com/photo-1493770348161-369560ae357d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80"></iframe>
    </figure>

  </div>
  <div class="column">
    <ul>
    <% @categories.each do | category | %>
      <li> 🥙 <%= link_to category.name, category %></li>
    <% end %>
  </ul>
  </div>
   </div>

app/views/categories/show.html.erb
<h1 class="title is-1"><%=@category.name %></h1>

<div class="columns">
  <div class="column">
  <figure class="image is-16by9">
      <iframe class="has-ratio" width="640" height="360" src="https://images.unsplash.com/photo-1606787366850-de6330128bfc?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=870&q=80"></iframe>
    </figure>

  </div>
  <div class="column">
    <ul>
    <% @category.recipes.each do |recipe| %>
      <li>🥗 <%= link_to recipe.title, recipe %></li>
    <%end%>
  </ul>
  </div>
   </div>

app/views/home/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <p class="title">
      Welcome to the amazing Recipe directory!
    </p>
    <p class="subtitle">
      Learn to cook yummy stuff!
    </p>
  </div>
</section>

    <figure class="image is-16by9">
      <iframe class="has-ratio"  src="https://images.unsplash.com/photo-1605210057707-8ac4e88bad73?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1740&q=80"></iframe>
    </figure>

app/views/home/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <p class="title">
      Welcome to the amazing Recipe directory!
    </p>
    <p class="subtitle">
      Learn to cook yummy stuff!
    </p>
  </div>
</section>
<div class="container is-fluid">
  <div class="notification is-primary">
    This container is <strong>fluid</strong>: it will have a 32px gap on either side, on any
    viewport size.
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">
      <figure class="image is-512x512">
        <img src="https://cdn-icons-png.flaticon.com/512/3448/3448167.png" alt = "img">
      </figure>
    </a>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item"></a>

       <p><%= link_to "Home", root_path %></p>

      <a class="navbar-item"></a>
      <p><%= link_to "Categories", categories_path %></p>

      <a class="navbar-item"></a>
      <p><%= link_to "Recipe Directory", recipes_path %></p>

      <a class="navbar-item"></a>
      <p><%= link_to "About", about_path %></p>

      <a class="navbar-item"></a>
        🔎
        <%= form_tag(recipes_path, method: :get) do %>
        <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag ("Search") %>
        <%end%>

    </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroToRubyProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render "layouts/navbar" %>

    <%= yield %>
  </body>
</html>

app/views/recipe_ingredients/index.html.erb
<h1>RecipeIngredients#index</h1>
<p>Find me in app/views/recipe_ingredients/index.html.erb</p>

app/views/recipe_ingredients/show.html.erb
<h1>RecipeIngredients#show</h1>
<p>Find me in app/views/recipe_ingredients/show.html.erb</p>

app/views/recipes/index.html.erb
<h1 class="title is-1">Very Fancy Recipes!</h1>

<div class="columns">
  <div class="column">
  <figure class="image is-16by9">
      <iframe class="has-ratio" width="640" height="360" src="https://images.unsplash.com/photo-1485963631004-f2f00b1d6606?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1075&q=80"></iframe>
    </figure>

  </div>
  <div class="column">
    <ul>
    <% @recipes.each do | recipe | %>
      <li> 🥑 <%= link_to recipe.title, recipe %></li>
    <% end %>
  </ul>
  </div>
   </div>



<br>
<br>
  <%# <%= will_paginate @recipes, renderer: BulmaPagination::Rails %>
  <%= will_paginate @recipes %>

app/views/recipes/show.html.erb
<div class="tile is-ancestor">
  <div class="tile is-4 is-vertical is-parent">
    <div class="tile is-child box">
      <p class="title"><%=@recipe.title %></p>
      <p><iframe class="has-ratio" width="280" height="150" src="https://source.unsplash.com/360x360/?food"></iframe></p>
      <p><strong>🍔Category: <%= @recipe.category.name %></strong></p>
    </div>
    <div class="tile is-child box">
      <p class="title">Ingredients</p>
      <p><% @recipe.ingredients.each do | ingredient | %>
            <%= ingredient.name %>,
          <% end %></p>
    </div>
  </div>
  <div class="tile is-parent">
    <div class="tile is-child box">
      <p class="title">Directions</p>
      <p><%= @recipe.directions %></p>
    </div>
  </div>
</div>